# Generated by Django 5.1.7 on 2025-05-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline_date',
            field=models.DateField(null=True),
        ),
    ]
